name: test-R-macos
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - maste 
jobs:
  test:
    name: Test on macos-latest 
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install numpy
        python3 -m pip install git+https://github.com/Netflix/metaflow.git@R-dev
    - name: Set up R 
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3'

    - name: Install Metaflow R binding and its dependencies
      run: |
        Rscript -e 'install.packages(c("R6", "reticulate", "magrittr", "lubridate", "cli"), repos="https://cloud.r-project.org")'
        R CMD INSTALL .

    - name: Install R dependencies for tests
      run:
        Rscript -e 'install.packages(c("data.table", "caret", "glmnet", "Matrix", "rjson", "testthat", "knitr", "rmarkdown"), repos="https://cloud.r-project.org")'

    - name: Run unit tests
      run: cd tests; Rscript testthat.R

    - name: Run canary tests
      run: cd tests/canaries; bash run_canaries.sh R

    - name: Run integrated tests
      run: cd tests; LOCAL_TEST=1 Rscript run_tests.R